---
apiVersion: v2
name: gitlab-ci-pipelines-exporter
version: 0.3.8
appVersion: v0.5.10
description: Prometheus / OpenMetrics exporter for GitLab CI pipelines insights
home: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
sources:
  - https://github.com/mvisonneau/helm-charts/tree/main/charts/gitlab-ci-pipelines-exporter
maintainers:
  - name: mvisonneau
    email: maxime.visonneau@gmail.com
dependencies:
  - name: redis
    version: 22.0.7
    repository: "oci://registry-1.docker.io/bitnamicharts"
    condition: redis.enabled
