name: Release Helm charts (Pages)
on:
  push: { branches: [ main ] }
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions: { contents: write } # push to gh-pages + create releases
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: azure/setup-helm@v4
      - name: Sync chart dependencies
        run: |
          set -euo pipefail
          for d in charts/*/; do
            [ -f "$d/Chart.yaml" ] || continue
            helm dependency update "$d"   # refresh Chart.lock if Chart.yaml changed
            helm dependency build "$d"    # vendor into $d/charts for packaging
          done
      - uses: azure/setup-helm@v4
      - name: Build dependencies (if any)
        run: |
          for d in charts/*; do
            [ -f "$d/Chart.yaml" ] && helm dependency build "$d" || true
          done
      - uses: helm/chart-releaser-action@v1.6.0
        with:
          charts_dir: charts
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
